### ISSUE TITLE
Pull generates errors from starter app

### ISSUE THREAD

**Issue by rojagit** [aws-samples/aws-serverless-appsync-loyalty#5]
This is obviously a remnant of the starter app, but I am unable to pinpoint the cause, I think it is in the cloud (aws) and some clean up needs to take place there.

ec2-user:~/environment/unicorn-loyalty $ **awsmobile pull**

retrieving the latest backend awsmobile project information
awsmobile project's details logged at:
    awsmobilejs/#current-backend-info/backend-details.json
awsmobile project's specifications logged at:
    awsmobilejs/#current-backend-info/mobile-hub-project.yml
⠙ retrieving appsync: get data sources...Failed to create dynamoDB table AppSyncEventTable-QmyfsE1o
{ ResourceNotFoundException: Requested resource not found: Table: **AppSyncEventTable**-QmyfsE1o not found
    at Request.extractError (/home/ec2-user/.nvm/versions/node/v8.11.4/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/protocol/json.js:48:27)

**Comment by rojagit** [comment]
For some reason the Ctrl+Shift+F didnt work the last time, but grepping it I found this:

ec2-user:~/environment/unicorn-loyalty $ grep -l 'AppSyncEvent' . -r     
./awsmobilejs/backend/appsync/dataSources.json
./awsmobilejs/backend/appsync/resolvers.json
./awsmobilejs/#current-backend-info/appsync/dataSources.json
./awsmobilejs/#current-backend-info/appsync/resolvers.json

**Comment by rojagit** [comment]
I did this step but it (Old tables) keeps coming back. I will try removing #currentbackend.

"Go to the folder awsmobilejs/backend/appsync and delete the file resolvers.json and the folder resolver-mappings.

Now go to the folder appsync in the root of the application directory and copy the file resolvers.json and the folder resolver-mappings to the previous folder awsmobilejs/backend/appsync, replacing the deleted files."

There are so many nested appsync folders I wish there was a better naming standard.

**Comment by rojagit** [comment]
Removed the # folder, and it regen'd correctly

For some reason datasources.json was still having the old stuff, copied from old app dir, made no diff.
I also did npm install - no errors
Grep & Find All have no matches for the old tables any more but still errors out as above whether on pull or push.

Push also gives this error: appsync update failed
TypeError: Cannot read property 'dataSources' of undefined
    at Object.diff (/home/ec2-user/.nvm/versions/node/v8.11.4/lib/node_modules/awsmobile-cli/lib/backend-operations/appsync-operations/helpers/helper-dataSources.js:41:81)

**Comment by rojagit** [comment]
Re-did it and it was fine this time.
